FROM python:3.11-alpine

WORKDIR /app

RUN apk add python3-dev build-base linux-headers pcre-dev
COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

CMD [ "python", "-u", "scraper.py" ]
