FROM python:3.9-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends docker.io && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ./main.py .

CMD [ "python", "-u", "main.py" ]
