COUNTRIES = {
    "sg": ["sng"],
    "mn": ["uln"],
    "ec": ["uio"],
    "cl": ["san"],
    "lu": ["ste"],
    "ph": ["mnl"],
    "lt": ["vno"],
    "uy": ["mvd"],
    "uk": ["gla", "edi", "man", "lon"],
    "mt": ["mla"],
    "gr": ["ath"],
    "ar": ["bua"],
    "us": [
        "buf",
        "orl",
        "clt",
        "dal",
        "nyc",
        "atl",
        "den",
        "phx",
        "dtw",
        "las",
        "chi",
        "kan",
        "bdn",
        "hou",
        "sfo",
        "mia",
        "sjc",
        "bos",
        "ltm",
        "slc",
        "ash",
        "lax",
        "sea",
    ],
    "fr": ["bod", "par", "mrs"],
    "nl": ["ams"],
    "la": ["vte"],
    "kh": ["pnh"],
    "jp": ["tok"],
    "de": ["fra", "ber"],
    "hu": ["bud"],
    "it": ["rom", "mil"],
    "si": ["lju"],
    "lk": ["cmb"],
    "mk": ["skp"],
    "at": ["vie"],
    "bn": ["bwn"],
    "md": ["chi"],
    "co": ["bog"],
    "bs": ["nas"],
    "es": ["vlc", "bcn", "mad"],
    "pt": ["opo", "lis"],
    "ie": ["dub"],
    "bo": ["sre"],
    "ua": ["iev"],
    "cr": ["sjn"],
    "vn": ["hcm"],
    "za": ["jnb"],
    "in": ["mum", "del"],
    "ma": ["rab"],
    "au": ["per", "bne", "mel", "adl", "syd"],
    "ad": ["leu"],
    "se": ["sto"],
    "pa": ["pac"],
    "pl": ["gdn", "waw"],
    "li": ["qvu"],
    "mm": ["nyt"],
    "id": ["jak"],
    "me": ["tgd"],
    "pk": ["khi"],
    "no": ["osl"],
    "mx": ["qro"],
    "az": ["bak"],
    "ca": ["tor", "van", "mon"],
    "ae": ["dub"],
    "lv": ["rig"],
    "bg": ["sof"],
    "mo": ["mfm"],
    "pr": ["sju"],
    "ee": ["tll"],
    "my": ["kul"],
    "ve": ["car"],
    "uz": ["tas"],
    "sa": ["ruh"],
    "tw": ["tai"],
    "ba": ["sjj"],
    "hk": ["hkg"],
    "im": ["iom"],
    "al": ["tia"],
    "np": ["ktm"],
    "ch": ["zur"],
    "fi": ["hel"],
    "be": ["anr", "bru"],
    "kz": ["ura"],
    "pe": ["lim"],
    "dz": ["alg"],
    "kr": ["seo"],
    "ge": ["tbs"],
    "tr": ["ist"],
    "mc": ["mcm"],
    "ng": ["lag"],
    "nz": ["akl"],
    "cy": ["nic"],
    "dk": ["cph"],
    "ro": ["buc"],
    "il": ["tlv"],
    "sk": ["bts"],
    "rs": ["beg"],
    "is": ["rkv"],
    "cz": ["prg"],
    "gl": ["goh"],
    "bt": ["pbh"],
    "th": ["bkk"],
    "eg": ["cai"],
    "hr": ["zag"],
    "py": ["asu"],
    "bz": ["blp"],
    "gh": ["acc"],
    "bd": ["dac"],
    "am": ["evn"],
    "br": ["sao"],
}
